GET http://localhost:3000/api/users/649fc0074843a7796910d6f7/folders HTTP/1.1
Content-Type: application/json


###
POST http://localhost:3000/api/links HTTP/1.1
Content-Type: application/json

{
  "url": "https://line.me/ko",
  "userId": "649fc0074843a7796910d6f7"
}

###
DELETE http://localhost:3000/api/folders/649fd8bbe443cfcf1349c9db HTTP/1.1
Content-Type: application/json







